### ISSUE TITLE
How can I play mp3 from another domain?

### ISSUE THREAD

**Issue by Dingo64** [laurentvd/wavesurfer.swf#1]
The SWF fallback renders and plays SWFs from the same domain just fine but from another domain it only plays- doesn't render. Any fix for that?

**Comment by laurentvd** [comment]
Yes, this is a limitation of Flash, but there is an easy fix for it if you control the other domain. You can place a [crossdomain.xml!](http://www.adobe.com/devnet/articles/crossdomain_policy_file_spec.html) file on the other domain. The most allowing example would be something like this: 

```
<?xml version="1.0" ?>
<cross-domain-policy>
    <allow-access-from domain="*" />
</cross-domain-policy>
```

If you don't control the other domain however, there's no good solution. There are solutions where you proxy the remote file through your own webserver, but I wouldn't recommend doing that.

**Comment by laurentvd** [comment]
If you have a crossdomain in place, but it still isn't working, there might be a setting or two I have to change in the swf file. So just let me know if this works for you.

**Comment by Dingo64** [comment]
Thanks for fast reply.
I put crossdomain.xml on the server with mp3s before writing my initial post, so I think this might be something in the SWF.

**Comment by laurentvd** [comment]
I've changed the swf to load the policy file. It's been a while since I used Flash as my main platform, so I hope it's correct. I've tested it and it seemed I had to add CORS headers to the other domain's file for it to work. I'm guessing this depends on the browser (I used Chrome). 

You could test this by adding something like this to your .htaccess (or similar) file:

```
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Methods: "GET,POST,OPTIONS,DELETE,PUT"
```

Let me know if this works for you!

**Comment by Dingo64** [comment]
Yep, it's great now! Thank you!
